version: "3.5"
services:
  mongo:
    image: mongo:5
    container_name: swollen-mongo
    env_file:
      - conf.d/mongo.env
    ports:
      - 127.0.0.1:5301:27017
    networks:
      - swollen
    volumes:
      - ./mongo_dump:/dump:rw
      - mongo:/data/db:rw
    restart: always
  chroma:
    image: chromadb/chroma:latest
    container_name: swollen-chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    env_file:
      - conf.d/chroma.env
    ports:
      - 127.0.0.1:5302:8080
    volumes:
      - chroma:/chroma/chroma
    networks:
      - swollen
    restart: always
  express:
    image: mongo-express:latest
    container_name: swollen-express
    env_file:
      - conf.d/express.env
    ports:
      - 127.0.0.1:35001:8081
    networks:
      - swollen
    depends_on:
      - mongo
    restart: always

volumes:
  mongo:
    driver: local
  chroma:
    driver: local

networks:
  swollen:
    name: swollen
    driver: bridge
