version: "3.5"
services:
  mongo:
    image: mongo:latest
    container_name: swollen-mongo
    networks:
      - swollen
    volumes:
      - mongo:/data/db:rw
    restart: always
  express:
    image: mongo-express:latest
    container_name: swollen-express
    networks:
      - swollen
    ports:
      - 127.0.0.1:35000:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: swollen-mongo
    depends_on:
      - mongo
    restart: always
  chroma:
    image: chromadb/chroma:latest
    container_name: swollen-chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    volumes:
      - chroma:/chroma/chroma
    networks:
      - swollen
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: /chroma/chroma
    restart: always

volumes:
  mongo:
    driver: local
  chroma:
    driver: local

networks:
  swollen:
    name: swollen
    driver: bridge
